export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const PROFILE_LOADED = "PROFILE_LOADED";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOAD_FAILED = "PROFILE_LOAD_FAILED";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAILED = "UPDATE_FAILED";
export const IS_UPDATING = "IS_UPDATING";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const TAGS_LOADED = "TAGS_LOADED";
export const TAGS_LOADING = "TAGS_LOADING";
export const PROFILES_LOADING = "PROFILES_LOADING";
export const PROFILES_LOAD_SUCCESS = "PROFILES_LOAD_SUCCESS";
export const PROFILES_LOAD_FAIL = "PROFILES_LOAD_FAIL";
export const FOLLOWING_USER_STARTED = "FOLLOWING_USER_STARTED";
export const FOLLOWING_USER_SUCCESS = "FOLLOWING_USER_SUCCESS";
export const UNFOLLOWING_USER_SUCCESS = "UNFOLLOWING_USER_SUCCESS";
export const FOLLOWING_USER_FAIL = "FOLLOWING_USER_FAIL";
export const FETCHING_FOLLOWING_LIST = "FETCHING_FOLLOWING_LIST";
export const FOLLOWING_LIST_LOADED = "FOLLOWING_LIST_LOADED";
export const FOLLOWING_LIST_LOADED_FAILED = "FOLLOWING_LIST_LOADED_FAILED";
export const FOLLOWERS_LOADED = "FOLLOWERS_LOADED";
export const ArticleActionTypes = {
  ARTICLE_FETCH_SUCCESSFUL: "ARTICLE_FETCH_SUCCESSFUL",
  ARTICLE_FETCH_NOT_FOUND: "ARTICLE_FETCH_NOT_FOUND",
  CREATE_ARTICLE_SUCCESS: "CREATE_ARTICLE_SUCCESS",
  CREATE_ARTICLE_FALIURE: "CREATE_ARTICLE_FALIURE",
  EDIT_ARTICLE_SUCCESS: "EDIT_ARTICLE_SUCCESS",
  EDIT_ARTICLE_FALIURE: "EDIT_ARTICLE_FALIURE",
  DELETE_ARTICLE_SUCCESS: "DELETE_ARTICLE_SUCCESS",
  FETCH_ARTICLES_SUCCESS: "FETCH_ARTICLES_SUCCESS",
  RATE_ARTICLES_SUCCESS: "RATE_ARTICLES_SUCCESS",
  RATE_ARTICLE_FAILURE: "RATE_ARTICLE_FAILURE",
};
export const BOOKMARK_SUCCESS = "BOOKMARK_SUCCESS";
export const BOOKMARK_FAIL = "BOOKMARK_FAIL";
export const BOOKMARK_LIST_FETCHED = "BOOKMARK_LIST_FETCHED";
export const UNBOOKMARK_SUCCESS = "UNBOOKMARK_SUCCESS";
