export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const PROFILE_LOADED = "PROFILE_LOADED";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOAD_FAILED = "PROFILE_LOAD_FAILED";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAILED = "UPDATE_FAILED";
export const IS_UPDATING = "IS_UPDATING";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const TAGS_LOADED = "TAGS_LOADED";
export const TAGS_LOADING = "TAGS_LOADING";
export const ArticleActionTypes = {
  ARTICLE_FETCH_SUCCESSFUL: "ARTICLE_FETCH_SUCCESSFUL",
  ARTICLE_FETCH_NOT_FOUND: "ARTICLE_FETCH_NOT_FOUND",
  CREATE_ARTICLE_SUCCESS: "CREATE_ARTICLE_SUCCESS",
  CREATE_ARTICLE_FALIURE: "CREATE_ARTICLE_FALIURE",
  EDIT_ARTICLE_SUCCESS: "EDIT_ARTICLE_SUCCESS",
  EDIT_ARTICLE_FALIURE: "EDIT_ARTICLE_FALIURE",
  DELETE_ARTICLE_SUCCESS: "DELETE_ARTICLE_SUCCESS",
  FETCH_ARTICLES_SUCCESS: "FETCH_ARTICLES_SUCCESS",
};
